// GENERATED by tools/generate-protocol-release.mjs — do not edit by hand.
// Run `npm run protocol:release` after any core change or version bump.
//
// The protocol release id is bound into the signed bytes of the backend-auth and
// bundle-approval envelopes (issue #71). It is derived from this build's
// canonical crypto/protocol core, so a phone and a backend pinned to different
// protocol revisions carry different ids and fail closed with an explicit
// `protocol_release_rejected` rather than an opaque signature failure.
export const PROTOCOL_VERSION = "0.5.0";
export const PROTOCOL_CORE_DIGEST_SHA256 = "fcf94f48786f7354a4db34dde707302bd194d677d35bf7cb6e60958724217207";
export const PROTOCOL_RELEASE_ID = "0.5.0+core.fcf94f48786f7354";
