// GENERATED by tools/generate-protocol-release.mjs — do not edit by hand.
// Run `npm run protocol:release` after any core change or version bump.
//
// The protocol release id is bound into the signed bytes of the backend-auth and
// bundle-approval envelopes (issue #71). It is derived from this build's
// canonical crypto/protocol core, so a phone and a backend pinned to different
// protocol revisions carry different ids and fail closed with an explicit
// `protocol_release_rejected` rather than an opaque signature failure.
export const PROTOCOL_VERSION = "0.4.0";
export const PROTOCOL_CORE_DIGEST_SHA256 = "b499a290ec760a786de8c03c12132e7db53f96562e5bc486376da73ac6b3e135";
export const PROTOCOL_RELEASE_ID = "0.4.0+core.b499a290ec760a78";
