import { utf8Encode } from "./core/crypto/bytes.js";
import { sha256Hex } from "./core/protocol/canonical.js";
import { INTEGRITY_BYPASS_PARAM } from "./sw-integrity.js";

const MANIFEST_URL = new URL("../manifest-sha256.json", import.meta.url);
const PWA_ROOT_URL = new URL("../", import.meta.url);

// Full set of app-controlled resources the runtime integrity check must cover
// (issue #10). This is no longer just the signing/crypto sub-graph: it also
// covers the renderer/controller (app.js, kernel-frame.js, payment-view.js),
// the HTML the user reviews, the storage/webauthn modules, and the frame and
// backup helpers. The HTML <script>/<link> tags additionally carry SRI hashes
// generated by tools/generate-pwa-integrity-manifest.mjs.
export const APP_INTEGRITY_GRAPH = [
  "index.html",
  "kernel.html",
  "src/app.js",
  "src/approval-kernel.js",
  "src/api-client.js",
  "src/backup-recovery.js",
  "src/bank-signing-batch.js",
  "src/bootstrap.js",
  "src/frame-buster.js",
  "src/frame-messaging.js",
  "src/integrity.js",
  "src/json-schema-validate.js",
  "src/kernel-frame.js",
  "src/payment-view.js",
  "src/response-schemas.js",
  "src/polling-capabilities.js",
  "src/sign-task-worker.js",
  "src/signing-session.js",
  "src/signing-worker-pool.js",
  "src/storage.js",
  "src/styles.css",
  "src/sw-integrity.js",
  "src/webauthn.js",
  "src/core/crypto/bigint.js",
  "src/core/crypto/bytes.js",
  "src/core/crypto/circl-keyshare.js",
  "src/core/crypto/circl-signshare.js",
  "src/core/crypto/pkcs1v15.js",
  "src/core/crypto/threshold-rsa.js",
  "src/core/protocol/canonical.js",
  "src/core/protocol/envelopes.js",
  "src/core/protocol/signing.js"
];

function resourceUrl(path) {
  if (typeof path !== "string" || path.startsWith("/") || path.includes("..") || path.includes("\\")) {
    throw new Error("integrity resource path is invalid");
  }
  const url = new URL(path, PWA_ROOT_URL);
  // Defense in depth (#15): the literal ".." check above misses percent-encoded
  // traversal (e.g. "%2e%2e/secret") and other sequences the URL parser
  // normalizes upward. After resolution the probe URL MUST stay under the PWA
  // root (same origin, path prefix), otherwise we'd fetch — and trust the
  // manifest hash of — a resource outside the app.
  if (!url.href.startsWith(PWA_ROOT_URL.href)) {
    throw new Error("integrity resource path is invalid");
  }
  // Append the integrity-bypass parameter so the cache-first service worker
  // answers this probe network-first instead of returning the same cached bytes
  // the loader executed (issue #9). Static hosts ignore the query string.
  url.searchParams.set(INTEGRITY_BYPASS_PARAM, "1");
  return url;
}

async function responseBytes(url) {
  const response = await fetch(url, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`integrity fetch failed for ${url.pathname}`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

function filesByPath(manifest) {
  return new Map((manifest.files ?? []).map((entry) => [entry.path, entry.sha256]));
}

export async function loadIntegrityManifest() {
  const manifestUrl = new URL(MANIFEST_URL.href);
  manifestUrl.searchParams.set(INTEGRITY_BYPASS_PARAM, "1");
  const response = await fetch(manifestUrl, { cache: "no-store" });
  if (!response.ok) {
    throw new Error("app integrity manifest is unavailable");
  }
  const raw = await response.text();
  const manifest = JSON.parse(raw);
  if (manifest.version !== "pwa_integrity_manifest_v1" || manifest.algorithm !== "SHA-256") {
    throw new Error("app integrity manifest version is unsupported");
  }

  return {
    ...manifest,
    manifest_sha256: await sha256Hex(utf8Encode(raw)),
    files_by_path: filesByPath(manifest)
  };
}

export async function assertResourceIntegrity(manifest, path) {
  const expected = manifest?.files_by_path?.get(path);
  if (!expected) {
    throw new Error(`app integrity manifest does not pin ${path}`);
  }

  const actual = await sha256Hex(await responseBytes(resourceUrl(path)));
  if (actual !== expected) {
    throw new Error(`app integrity check failed for ${path}`);
  }
  return actual;
}

export async function assertResourcesIntegrity(manifest, paths) {
  await Promise.all(paths.map((path) => assertResourceIntegrity(manifest, path)));
}

export function assertAppIntegrity(manifest) {
  return assertResourcesIntegrity(manifest, APP_INTEGRITY_GRAPH);
}
